In [1]:
import pandas as pd

In [2]:

data = {
    "EmpID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Arun", "Priya", "Kumar", "Divya", "Rahul",
        "Meena", "Sathish", "Nila", "Vijay", "Kavya"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "IT",
        "HR", "Finance", "IT", "Sales", "Sales"
    ],
    "Age": [25, 29, 32, 27, 24, 35, 31, 28, 30, 26],
    "Salary": [
        35000, 42000, 58000, 39000, 30000,
        62000, 51000, 47000, 44000, 36000
    ],
    "Experience": [2, 5, 8, 3, 1, 10, 7, 4, 6, 2],
    "City": [
        "Chennai", "Madurai", "Chennai", "Coimbatore",
        "Salem", "Chennai", "Madurai", "Coimbatore",
        "Chennai", "Salem"
    ]
}


df = pd.DataFrame(data)

print(df)

   EmpID     Name Department  Age  Salary  Experience        City
0    101     Arun         IT   25   35000           2     Chennai
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

In [3]:
import pandas as pd

data = {
    "EmpID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Arun", "Priya", "Kumar", "Divya", "Rahul",
             "Meena", "Sathish", "Nila", "Vijay", "Kavya"],
    "Department": ["IT", "HR", "IT", "Finance", "IT",
                   "HR", "Finance", "IT", "Sales", "Sales"],
    "Age": [25, 29, 32, 27, 24, 35, 31, 28, 30, 26],
    "Salary": [35000, 42000, 58000, 39000, 30000,
               62000, 51000, 47000, 44000, 36000],
    "Experience": [2, 5, 8, 3, 1, 10, 7, 4, 6, 2],
    "City": ["Chennai", "Madurai", "Chennai", "Coimbatore",
             "Salem", "Chennai", "Madurai", "Coimbatore",
             "Chennai", "Salem"]
}

df = pd.DataFrame(data)

print("First 5 rows:")
display(df.head(5))

print("Last 3 rows:")
display(df.tail(3))

print("Number of rows and columns:")
print(df.shape)

print("Column data types:")
print(df.dtypes)

First 5 rows:

   EmpID   Name Department  Age  Salary  Experience        City
0    101   Arun         IT   25   35000           2     Chennai
1    102  Priya         HR   29   42000           5     Madurai
2    103  Kumar         IT   32   58000           8     Chennai
3    104  Divya    Finance   27   39000           3  Coimbatore
4    105  Rahul         IT   24   30000           1       Salem

Last 3 rows:

   EmpID   Name Department  Age  Salary  Experience        City
7    108   Nila         IT   28   47000           4  Coimbatore
8    109  Vijay      Sales   30   44000           6     Chennai
9    110  Kavya      Sales   26   36000           2       Salem

Number of rows and columns:
(10, 7)
Column data types:
EmpID         int64
Name            str
Department      str
Age           int64
Salary        int64
Experience    int64
City            str
dtype: object

## Filter employee records ##

In [4]:

import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

result = df[(df['Department'] == 'IT') & (df['Salary'] > 40000)]

print(result)

   EmpID   Name Department  Age  Salary  Experience     City
2    103  Kumar         IT   32   58000           8  Chennai

## Sort the data¶ ##

In [6]:
import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

result = df.sort_values(by='Salary', ascending=False)

print(result[['Name', 'Department', 'Salary']])

    Name Department  Salary
2  Kumar         IT   58000
1  Priya         HR   42000
3  Divya    Finance   39000
0   Arun         IT   35000

## Calculate summary statistics ##

In [7]:
import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

print("Mean Salary:", df['Salary'].mean())
print("Maximum Salary:", df['Salary'].max())
print("Minimum Salary:", df['Salary'].min())
print("Median Salary:", df['Salary'].median())

print("Average Age:", df['Age'].mean())

Mean Salary: 43500.0
Maximum Salary: 58000
Minimum Salary: 35000
Median Salary: 40500.0
Average Age: 28.25

## Group by department ##

In [8]:
import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

result = df.groupby('Department').agg(
    Number_of_Employees=('EmpID', 'count'),
    Average_Salary=('Salary', 'mean'),
    Highest_Salary=('Salary', 'max')
)

result = result.sort_values(
    by='Average_Salary',
    ascending=False
)

print(result)

            Number_of_Employees  Average_Salary  Highest_Salary
Department
IT                            2         46500.0           58000
HR                            1         42000.0           42000
Finance                       1         39000.0           39000

## Create a new column ##

In [9]:
import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

df['AnnualSalary'] = df['Salary'] * 12

print(df[['Name', 'Salary', 'AnnualSalary']])

    Name  Salary  AnnualSalary
0   Arun   35000        420000
1  Priya   42000        504000
2  Kumar   58000        696000
3  Divya   39000        468000

## Find missing and duplicate values ##

In [10]:

import pandas as pd

# Create the employee DataFrame
df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

df_copy = df.copy()

df_copy.loc[0, 'City'] = None

df_copy = pd.concat(
    [df_copy, df_copy.iloc[[1]]],
    ignore_index=True
)

print("DataFrame with missing value and duplicate row:")
print(df_copy)

print("\nMissing Values:")
print(df_copy.isnull().sum())

df_copy['City'] = df_copy['City'].fillna('Unknown')

print("\nAfter filling missing values:")
print(df_copy)

df_copy = df_copy.drop_duplicates()

print("\nAfter removing duplicate rows:")
print(df_copy)

DataFrame with missing value and duplicate row:
   EmpID   Name Department  Age  Salary  Experience     City
0    101   Arun         IT   25   35000           2      NaN
1    102  Priya         HR   29   42000           5  Madurai
2    103  Kumar         IT   32   58000           8  Chennai
3    104  Divya    Finance   27   39000           3  Chennai
4    102  Priya         HR   29   42000           5  Madurai

Missing Values:
EmpID         0
Name          0
Department    0
Age           0
Salary        0
Experience    0
City          1
dtype: int64

After filling missing values:
   EmpID   Name Department  Age  Salary  Experience     City
0    101   Arun         IT   25   35000           2  Unknown
1    102  Priya         HR   29   42000           5  Madurai
2    103  Kumar         IT   32   58000           8  Chennai
3    104  Divya    Finance   27   39000           3  Chennai
4    102  Priya         HR   29   42000           5  Madurai

After removing duplicate rows:
   EmpID   Name Department  Age  Salary  Experience     City
0    101   Arun         IT   25   35000           2  Unknown
1    102  Priya         HR   29   42000           5  Madurai
2    103  Kumar         IT   32   58000           8  Chennai
3    104  Divya    Finance   27   39000           3  Chennai

## Use conditional logic ##

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

df['SalaryLevel'] = np.where(
    df['Salary'] >= 50000, 'High',
    np.where(df['Salary'] >= 40000, 'Medium', 'Low')
)

print(df[['Name', 'Salary', 'SalaryLevel']])

    Name  Salary SalaryLevel
0   Arun   35000         Low
1  Priya   42000      Medium
2  Kumar   58000        High
3  Divya   39000         Low

## Work with a second DataFrame ##

In [12]:

import pandas as pd

df = pd.DataFrame({
    'EmpID': [101, 102, 103, 104],
    'Name': ['Arun', 'Priya', 'Kumar', 'Divya'],
    'Department': ['IT', 'HR', 'IT', 'Finance'],
    'Age': [25, 29, 32, 27],
    'Salary': [35000, 42000, 58000, 39000],
    'Experience': [2, 5, 8, 3],
    'City': ['Chennai', 'Madurai', 'Chennai', 'Chennai']
})

dept_avg = df.groupby('Department')['Salary'].mean()

highest_dept = dept_avg.idxmax()
highest_avg = dept_avg.max()

print("Department with highest average salary:", highest_dept)
print("Highest average salary:", highest_avg)

overall_avg = df['Salary'].mean()
print("\nOverall average salary:", overall_avg)

above_avg = df[df['Salary'] > overall_avg]

print("\nEmployees earning above overall average:")
print(above_avg[['Name', 'Department', 'Salary']])

Department with highest average salary: IT
Highest average salary: 46500.0

Overall average salary: 43500.0

Employees earning above overall average:
    Name Department  Salary
2  Kumar         IT   58000